version: '3.7'
services:
  redis:
    image: 'redis:alpine'
    expose:
      - '6379'
    networks:
      default:
        aliases:
          - redisservice
  asyncworker:
    build:
      context: .
      dockerfile: ./Dockerfile.asyncworker
    networks:
      - default
    volumes:
      - ./asyncworker:/usr/src/apps/asyncworker
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.webapp
    ports:
      - '127.0.0.1:6543:6543'
    networks:
      - default
    volumes:
      - ./webapp:/usr/src/apps/webapp
  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - '127.0.0.1:9000:9001'
    volumes:
      - './miniodata:/data'
    networks:
      - default
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address :9001 /data
volumes:
  miniodata:
  webapp:
  asyncworker:
networks:
  default:
